name: Release Manager

on:
  release:
    types: [published]
    branches:
      - master

jobs:
  SBML_to_Discord:
    env: 
      DISCORD_WEBHOOK_RELEASE: ${{secrets.DISCORD_WEBHOOK_RELEASE}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
      fail-fast: true
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Model
      run: |
        python .github/tests/tsv_to_sbml.py
    - name: Report to Discord server
      run: |
        tar -czvf WormJam.tar.gz WormJam.xml
        python .github/tests/release_manager.py "$DISCORD_WEBHOOK_RELEASE" $GITHUB_REPOSITORY $GITHUB_REF

